name: Main CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test-pieServer:
    name: Test pieServer code
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        working-directory: ./pieServer
        run: npm ci
      - name: Test code
        working-directory: ./pieServer
        run: npm test

  test-nginx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2

      - name: Run docker compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./compose.yaml"

      - name: Execute tests in the running services
        run: |
          docker compose exec nginx /usr/bin/env \
          curl -f "http://localhost:80" || exit 1

  build:
    name: Build Docker Containers
    needs: [test-pieServer, test-nginx]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker compose build
